#!/bin/bash

MYID=20221031192031
export testlocation="$1"
overwrite=0
if [ "$2" == "--overwrite" ]; then
  overwrite=1
fi

mkdir -p "$testlocation"
mkdir -p "$testlocation/zet"

cp zettel-template "$testlocation"
[ ! -f "$testlocation/.gitignore" ] && cp .gitignore "$testlocation"

[ -f "$testlocation/README.md" ] || echo '- [WIP work in progress](/zet/20221008042814/README.md)' >> "$testlocation/README.md"

for id in $( ./graphquery id $MYID refs ); do
  echo $id
  if [[ $overwrite == "0" ]]; then
    if [ ! -d "$testlocation/zet/$id" ]; then
      echo "it is not there"
    fi
    if [ ! -d "$testlocation/zet/$id" ]; then
      cp -r zet/$id "$testlocation/zet"
      echo "copying"
    else
      echo "not"
    fi
  else
    cp -r zet/$id "$testlocation/zet"
  fi
done

#awk '
#BEGIN { cmd = "cp -r " }
#{ cmd = cmd "zet/" $0 " " }
#END {
#  cmd = cmd ENVIRON["testlocation"] "/zet"
#  print cmd
#  system(cmd)
#}
#'

# symlinks
#cd "$testlocation"
#ln -sr zet/20221006032546/zetcmd zc
#ln -sr zet/20221013021614/graphbrowser zkvr
#ln -sr zet/20221028172836/Dockerfile Dockerfile
#ln -sr zet/20221027011800/zetwrap zetcli
#ln -sr zet/20221013221136/graphquery graphquery
#ln -sr zet/20221006032546 implementation
#ln -sr zet/20221028172836/rundocker rundocker
#ln -sr zet/20221028173620/bin yq_binaries
#ln -sr yq_binaries/yq_linux_amd64 yq
#cd -
