#!/bin/bash
# script for checking stuff on the main page
export CARD_ID=20221009192000
export mydir="$2"
references=$(mktemp)
found=$(mktemp)

echo "checking stuff on the main page... $@" >/dev/stderr

$prog refs $CARD_ID > $references # get references
indexdothtml="$mydir/../../README.md"
# search for the IDs we found
grep -Eo -f $references "$indexdothtml" > $found
{
  echo "Reference count:  $(wc -l $found) of $(wc -l $references)"
  echo "Missing:"
  grep -v -f $found $references
} > $mydir/missing

export snippetcommand="cat $mydir/missing"

#--------------------------------------------------------------------------------
# replace a snippet code using awk
awk '
BEGIN { pr = 0 }
!pr { print }
/```/ && pr { pr = 0; print; next }
/```/ && !pr {
  command = ENVIRON["snippetcommand"]
  print(command)
  command = command " 2>/dev/null"
  while ((command | getline) > 0) {
    print $0
  }
  close(command)
  pr = 1
}
' "$mydir/README.md" > "$found"

mv "$found" "$mydir/README.md"
rm "$references"
exit 0
