#!/bin/bash
# script for checking stuff on the main page
export CARD_ID=20221009192000
export implementation=20221006032546
export mydir="$2"
references=$(mktemp)
found=$(mktemp)

echo "checking stuff on the main page... $@" >/dev/stderr

indexdothtml="$mydir/../../README.md"

$prog refs $CARD_ID > $references # get references
# search for the IDs we found
#zet/$implementation/parseids $indexdothtml | sort -u > $found
{
  echo "Missing:"
  ./query2 id $CARD_ID : not { file $indexdothtml }
  echo "Extra:"
  ./query2 file $indexdothtml not { id $CARD_ID : } #not { id $CARD_ID }
} > $mydir/missing

export snippetcommand="cat $mydir/missing"
zet/$implementation/insertsnippet $CARD_ID $mydir/missing

exit 0
#--------------------------------------------------------------------------------
# replace a snippet code using awk
#awk '
#BEGIN { pr = 0 }
#!pr { print }
#/```/ && pr { pr = 0; print; next }
#/```/ && !pr {
#  command = ENVIRON["snippetcommand"]
#  #command = command " 2>/dev/null"
#  while ((command | getline) > 0) {
#    print $0
#  }
#  close(command)
#  pr = 1
#}
#' "$mydir/README.md" > "$found"
#
#mv "$found" "$mydir/README.md"
#rm "$references"
#exit 0
