#!/bin/bash

awk '
{
  id = $1
}
function addtag(tag) {
  system("./add-tag.sh -t " tag " " id) #script
}
$2 ~ /auto/ { # add language keywords to autogenerated content from scripts
  split($2,arr,"/")
  gsub(/^.*auto-/,"",$2)
  gsub(/\.md$/,"",$2)
  lang = $2
  addtag(lang)
  addtag("script")
  next
}
$2 ~ /command/ { addtag("command") }
$2 ~ /to-try-list/ { addtag("to-try-list") }
' zet_to_source_file
