#!/usr/bin/awk -f
BEGIN {
  inter = "./queryinterpreter"
  #print "interpreter", inter
}
function interpretme(subcommand) { # interpret the rest of this line as a subcommand. return the command string to read and close.
  "mktemp" | getline tf
  print "interpret", subcommand
  print subcommand > tf
  close(tf)
  command = inter " " tf
  return command
}
/^ / { gsub(/^ +/,"") }
/ $/ { gsub(/ +$/,"") }
/^#[a-zA-Z0-9-]+$/ {
  tag = $0
  gsub(/^#/,"",tag)
  print "read tag list", tag
  command = "implementation/parseids tagindex/" tag ".md" # really simple
  system(command)
}
$(NF-1) == "~" {
  query=$NF
  print "start query", query
  NF -= 2
  command = interpretme($0)
  while ((command | getline) > 0){
    print "|", $0
  }
  close(command)
  print "like", query
  print "done query", query
}
