#!/bin/bash

commandconcept=20221009014200 #concept of a command
KB_ID=20221003151443 #zet/20221003151443/README.md # kb
export LC_COLLATE=C

donethings=$(mktemp)
./graphquery '@done' '@hub' refs > $donethings

#echo "#"
#echo "# things attached to command hub that are not marked as commands"
#echo "#"
#zet/20221023085822/walkquery --human <( echo $commandconcept) refs \
#  not <( ./graphquery taglist 'command,hub,kb_import' ) \
#  not $donethings

bashtricks=20221003151299

echo "#"
echo "# unlabled scripts and commands and things "
echo "#"
./graphquery --human taglist 'bash' \
  or <( ./graphquery id $bashtricks refs ) \
  not <( ./graphquery taglist 'meta,command,hub,kb_import,tip,trick,tool,repo,install,syntax,util,script' )

echo ""
echo "--------------------------------------------------------------------------------"
echo ""

echo "#"
echo "# tags"
echo "#"
ls tagindex | sort | awk '
{ gsub(/\.md$/,"") }
{
  c = substr($1,1,1)
  if (box[c]) { box[c] = box[c] " " }
  box[c] = box[c] $0
}
END { asort(box); for (c in box) { print box[c] } }
'

echo ""
echo "--------------------------------------------------------------------------------"
echo ""

rm "$donethings" # del tempfile
