#!/bin/bash

commandconcept=20221009014200 #concept of a command
KB_ID=20221003151443 #zet/20221003151443/README.md # kb
export LC_COLLATE=C

echo "#"
echo "# things attached to command hub that are not marked as commands"
echo "#"
zet/20221023085822/walkquery --human <( echo $commandconcept) refs not <( ./graphquery taglist 'command,hub' )

echo ""
echo "--------------------------------------------------------------------------------"
echo ""

echo "#"
echo "# tags"
echo "#"
ls tagindex | sort | awk '
{ gsub(/\.md$/,"") }
{
  c = substr($1,1,1)
  if (box[c]) { box[c] = box[c] " " }
  box[c] = box[c] $0
}
END { asort(box); for (c in box) { print box[c] } }
'

echo ""
echo "--------------------------------------------------------------------------------"
echo ""

