#!/usr/bin/awk -f
BEGIN { foundstartsnip = foundendsnip = 0 }
#print first file up to snippet, then save the rest after snippet.
#print second file, then print saved stuff after snippet.
#end effect is inserting it into file
#add index paremter to alter other snippets
{ snipline = 0 }
/^```/ { snipline = 1 }
ARGIND == 1 {
  if (!foundstartsnip) {
    print
    if (snipline) foundstartsnip = 1
  } else if (!foundendsnip) {
    if (snipline) foundendsnip = 1
  }
  if (foundendsnip) save[l++] = $0
}
ARGIND == 2 { print }
END { for (n = 0; n < l; n++) print save[n] }
