#!/usr/bin/awk -f
ENDFILE {
  if (last ~ /^    #/){ # take tags from last line of prev file
    gsub(/^ +/,"") # strip leading spaces
    gsub(/ +$/,"") # strip trailing spaces
    print "tags", fileid, $0
  }
  if (empties > 3) { # 3 empty lines allowed around references headings for zettel format
    print "emptylines", fileid, empties
  }
}
/^# [Rr]elated/ { scanning = 1 }
!scanning { next }
{ last = $0 }
scanning && /^$/ { empties++ }
