#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage $0 (ID | path to README.md)"
  exit 1
fi

if [ -f "$1" ]; then # passing in file parameter
  export id=$(echo "$1" | awk -F / '{ print $(NF-1) }')
else
  export id=$1
fi

awk '
BEGIN {
  id = ENVIRON["id"]
  print 2, id
  ids[id] = 1
  command = "./zc refs " id " 2>/dev/null"
  while ((command | getline nextid) > 0) {
    ids[nextid] = 1
  }
  close(command)
  for (i in ids) print 1, i
}
' | awk '
{
  weight = $1
  id = $2

  file = "zet/" id "/README.md" 
  command = "grep -Eo \047\\w+\047 " file " | tr A-Z a-z"
  while ((command | getline word) > 0) {
    print weight, word
  }
  close(command)

  command = "head " file " | grep -Eo \047\\w+\047 | tr A-Z a-z"
  while ((command | getline word) > 0) {
    print weight * 5, word
  }
  close(command)
}
' | awk '
{
  score = $1
  word = $2
  scores[word] = scores[word] + score
}
END {
  for (w in scores) {
    print scores[w], w
  }
}
' | sort -n
