#!/bin/bash

awk '
BEGINFILE { snip = 0 }
/```/ { snip = !snip }
!snip && /^ *- / {
  m = match($0, /^ */)
  space = RLENGTH
  if (space - lastspace > 2) { print FILENAME, $0 }
  lastspace = space
}
/^# Related/ { nextfile }
' $(find zet -name README.md)
