#!/bin/bash

highlevel=20221011182140 # high level machine overview from notes template
for cardid in $(zet/20221014025416/tagboundary $highlevel template); do
  for refid in $(./zc refs $cardid); do
    echo "$cardid $refid"
  done
done | awk '
BEGIN {
  print "graph TD;"
  headings[""]=0
}
function lookup(id) {
  if (id in headings) return headings[id]
  fn = "zet/"id"/README.md"
  getline < fn
  close(fn)
  gsub(/^# /,"")
  headings[id] = $0
  return $0
}
$1 < $2 {
  src = $1
  dst = $2
  print "  " lookup(src), "--", lookup(dst)
}
'
