#!/bin/bash
MYID=20221013021614
IMPL=20221006032546

if [ -z "$EDITOR" ]; then
  EDITOR=$(which nvim 2>/dev/null || which vim 2>/dev/null || which vi 2>/dev/null )
fi
if [ -z "$prog" ]; then
  prog="./zc"
fi

# running preview subprocess
if [ "$1" == "video" ]; then
  if [ "$3" == "stat" ]; then
    zet/$IMPL/previewgit
  else
    bat --color=always $2
  fi
  exit 0
fi

# main loop
going=1
export prevdoc="README.md" # quick way to fix a bug before it happens
export doc="README.md"
if [ ! -z "$1" ]; then
  export doc="$1"
fi
selection=$(mktemp)
while [ 1 == "$going" ]; do
  awk '
  BEGIN {
    print "edit"
    print "/deep"
    print "back"
    print "enrich"
    if (ENVIRON["TMUX"] ~ /tmux/) {
      print "tab"
    }
    doc = ENVIRON["doc"]
    if (doc != "README.md") {
      id = doc
      gsub(/^zet\//,"",id)
      gsub(/\/.*$/,"",id)
      if (id != "README.md") {
        print "spawn", id
        print "spawnedit", id
      }
      print "link"
      print "unlink"
    } else {
      id = 0
    }
    print "stat"
    print "quit"
    fflush()
  }
  /^ *- \[.*\]\(\/zet\/[0-9]+\/README.md\)/ {
    print "goto", $0
    fflush()
  }
  ' "$doc" | fzf --preview="$0 video '$doc' {}" --bind "up:preview-up,down:preview-down" "--preview-window=up,75%" --prompt="$doc :" > "$selection"
  sel="$(cat $selection)"
  act=$(cat $selection | awk '{print $1}')
  id=$(echo "$doc" | awk -F / '{ print $(NF-1) }')
  if [ "$act" == "quit" ]; then
    exit 0
  elif [ "$act" == "goto" ]; then
    export prevdoc="$doc"
    doc=$(awk '{
      gsub(/\).*$/,"")
      gsub(/^.*\(/,"")
      gsub(/^\//,"")
      print
    }' $selection)
    echo "changed to $doc"
  elif [ "$act" == "unlink" ]; then
    echo "DEBUG: current id is $id"
    awk '
      /^ *- \[.*\]\(\/zet\/[0-9]+\/README.md\)/ {
        print $0
        fflush()
      }
    ' "$doc" | fzf > "$selection"
    if [ ! -z "$id" ]; then
      zet/$IMPL/parseids $selection | sort -u | xargs -n 1 $prog unlink "$id"
    fi
    #sleep 1
  elif [ "$act" == "link" ]; then
    $prog connectome -m | awk '{print $1}' > $selection
    if [ ! -z "$id" ]; then
      zet/$IMPL/parseids $selection | sort -u | xargs -n 1 $prog addref -t "$id"
    fi
    ./zc enrich_links_single "$id"
    #sleep 1
  elif [ "$act" == "back" ]; then
    temp="$doc"
    doc="$prevdoc"
    prevdoc="$temp" # would expect back to work again?
    echo "back to $doc"
  elif [ "$act" == "edit" ]; then
    if [ ! -z $TMUX ]; then
      tmux new-window $EDITOR "$doc"
    else
      $EDITOR "$doc"
    fi
  elif [ "$act" == "tab" ]; then
    tmux new-window $0 "$doc"
  elif [ "$act" == "/deep" ]; then
    if [ -z $TMUX ]; then
      newid=$(zet/$MYID/connectome_deep | fzf | awk '{print $1}')
      export prevdoc="$doc"
      export doc=zet/$newid/README.md
    else
      tf=$(mktemp)
      zet/$MYID/connectome_deep | fzf -m | awk '{print $1}' | sort -u > $tf
      for f in $(cat $tf); do
        tmux new-window -n 'explore' $0 zet/$f/README.md
      done
      rm "$tf"
    fi
  elif [ "$act" == "spawn" ]; then
    id=$(echo "$doc" | awk -F / '{print $(NF-1)}')
    read -p "enter title> " title
    newid=$(./zc new -t "$title" -r "$id" | awk '/created zet ID/ { print $NF }')
    echo "spawned $newid"
    ./zc addref -t $id $newid
    ./zc enrich_links_single $id
    ./zc enrich_links_single $newid
  elif [ "$act" == "stat" ]; then
    if which lazygit; then
      lazygit
    else
      git status # i guess
      sleep 2
    fi
  elif [ "$act" == "spawnedit" ]; then
    id=$(echo "$doc" | awk -F / '{print $(NF-1)}')
    read -p "enter title> " title
    newid=$(./zc new -t "$title" -r "$id" | awk '/created zet ID/ { print $NF }')
    echo "spawned $newid"
    ./zc addref -t $id $newid
    ./zc enrich_links_single $id
    ./zc enrich_links_single $newid
    if [ ! -z $TMUX ]; then
      tmux new-window $EDITOR -p "zet/$id/README.md" "zet/$newid/README.md"
    fi
  elif [ "$act" == "enrich" ]; then
    echo "are you sure? you should make sure you save your changes to git first."
    read -p "answer (y/n): " answer
    if [ $answer == "y" ]; then
      $prog enrich
      $prog enrich
    else
      echo $answer
      sleep 1
    fi
  fi
done
rm "$selection"
