#!/bin/bash

find zet -name README.md | xargs awk '
/^# / {
  gsub(/^# /,"")
  if (length() > 72) print length(), FILENAME, $0
  nextfile
}
' | sort -nr | grep -v <( ./graphquery @DEL ) # hide deleted IDs
