#!/bin/bash
MY_ID=20221012144502

recent=$(date --date='1 day ago' --iso)

echo "not enabled yet"
exit 0

find zet -newermt "$recent" -name README.md 2>/dev/null | while read line; do
  export filename=$line
  git log --date=unix -- "$filename" | awk '
  BEGIN { OFS = "\t" }
  /^Date/ {
    epoch = $2
    "date --date @" epoch " --iso" | getline isodate
    print epoch, isodate, ENVIRON["filename"]
    exit 0
  }'
  shift
done
